export const CART_ADD_ITEM ="CART_ADD_ITEM";
export const CART_REMOVE_ITEM ="CART_REMOVE_ITEM";

export const CART_SAVE_SHIPIING_ADDRESS="CART_SAVE_SHIPIING_ADDRESS";

export const CART_SAVE_PAYMENTMETHOD ="CART_SAVE_PAYMENTMETHOD";

export const CART_EMPTY ="CART_EMPTY";