export const CREATE_ORDER_REQUEST ="CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS ="CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAILED ="CREATE_ORDER_FAILED";
export const CREATE_ORDER_RESET ="CREATE_ORDER_RESET";

export const ORDER_DETAILS_REQUEST ="ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS ="ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAILED ="ORDER_DETAILS_FAILED";

export const ORDER_PAY_REQUEST ="ORDER_PAY_REQUEST";
export const ORDER_PAY_SUCCESS ="ORDER_PAY_SUCCESS";
export const ORDER_PAY_FAILED ="ORDER_PAY_FAILED";
export const ORDER_PAY_RESET ="ORDER_PAY_RESET";

export const MY_ORDER_LIST_REQUEST ="MY_ORDER_LIST_REQUEST";
export const MY_ORDER_LIST_SUCCESS ="MY_ORDER_LIST_SUCCESS";
export const MY_ORDER_LIST_FAILED ="MY_ORDER_LIST_FAILED";

export const ORDER_LIST_REQUEST ="ORDER_LIST_REQUEST";
export const ORDER_LIST_SUCCESS ="ORDER_LIST_SUCCESS";
export const ORDER_LIST_FAILED ="ORDER_LIST_FAILED";

export const ORDER_DELETE_REQUEST ="ORDER_DELETE_REQUEST";
export const ORDER_DELETE_SUCCESS ="ORDER_DELETE_SUCCESS";
export const ORDER_DELETE_FAILED ="ORDER_DELETE_FAILED";
export const ORDER_DELETE_RESET ="ORDER_DELETE_RESET";

export const ORDER_DELIVER_REQUEST ="ORDER_DELIVER_REQUEST";
export const ORDER_DELIVER_SUCCESS ="ORDER_DELIVER_SUCCESS";
export const ORDER_DELIVER_FAILED ="ORDER_DELIVER_FAILED";
export const ORDER_DELIVER_RESET ="ORDER_DELIVER_RESET";

export const ORDER_SUMMARY_REQUEST ="ORDER_SUMMARY_REQUEST";
export const ORDER_SUMMARY_SUCCESS ="ORDER_SUMMARY_SUCCESS";
export const ORDER_SUMMARY_FAILED ="ORDER_SUMMARY_FAILED";
export const ORDER_SUMMARY_RESET ="ORDER_SUMMARY_RESET";