export const USER_SIGNIN_REQUEST ="USER_SIGNIN_REQUEST";
export const USER_SIGNIN_SUCCESS ="USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FALIED ="USER_SIGNIN_FALIED";
export const USER_SIGNIN_SIGNOUT="USER_SIGNIN_SIGNOUT";

export const USER_REGISTER_REQUEST ="USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS ="USER_REGISTER_SUCCESS";
export const USER_REGISTER_FALIED ="USER_REGISTER_FALIED";


export const USER_DETAILS_REQUEST ="USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS ="USER_DETAILS_SUCCESS";
export const USER_DETAILS_FALIED ="USER_DETAILS_FALIED";
export const USER_DETAILS_RESET="USER_DETAILS_RESET";

export const PROFILE_UPDATE_REQUEST = "PROFILE_UPDATE_REQUEST";
export const PROFILE_UPDATE_SUCCESS ="PROFILE_UPDATE_SUCCESS";
export const PROFILE_UPDATE_FAILED ="PROFILE_UPDATE_FAILED";
export const PROFILE_UPDATE_RESET="PROFILE_UPDATE_RESET";

export const USER_LIST_REQUEST ="USER_LIST_REQUEST";
export const USER_LIST_SUCCESS ="USER_LIST_SUCCESS";
export const USER_LIST_FAILED = "USER_LIST_FAILED";

export const USER_DELETE_REQUEST ="USER_DELETE_REQUEST";
export const USER_DELETE_SUCCESS ="USER_DELETE_SUCCESS";
export const USER_DELETE_FAILED = "USER_DELETE_FAILED";
export const USER_DELETE_RESET ="USER_DELETE_RESET";


export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST";
export const USER_UPDATE_SUCCESS ="USER_UPDATE_SUCCESS";
export const USER_UPDATE_FAILED ="USER_UPDATE_FAILED";
export const USER_UPDATE_RESET="USER_UPDATE_RESET";